# Generated by Django 3.0 on 2021-04-28 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=150, verbose_name='Nom et prénoms')),
                ('code_matricule', models.CharField(max_length=10, verbose_name='Code matricule')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est Actif')),
            ],
            options={
                'verbose_name': 'chauffeur',
                'verbose_name_plural': 'chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('DGE', 'Dir. Générale(DGE)'), ('DCF', 'Dir. Financière(DCF)'), ('DRH', 'Dir. RH(DRH)'), ('DEX', 'Dir. Exploitation(DEX)'), ('DET', 'Dir. Technique(DET)'), ('DCM', 'Dir. Commerciale(DCM)'), ('SMG', 'Moyens Generaux(SMG)'), ('FHY', 'fret Hydrocarbure(FHY)'), ('FSB', 'fret boisson(FSB)'), ('FHP', 'fret huile de palm(FHP)'), ('FTC', 'fret conteneurs(FTC)'), ('FCS', 'fret canne à sucre(FCS)'), ('FDI', 'fret divers(FDI)'), ('LEV', 'levage(LEV)'), ('LOC', 'location de surfaces(LOC)'), ('SDI', 'services divers(SDI)'), ('RAV', 'revenus à ventiler(RAV)'), ('PAF', 'Prestation Accessoir(PAF)'), ('COL', 'fret Colis lourds(COL)')], max_length=50)),
                ('code_matricule', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('DGE', 'Dir. Générale(DGE)'), ('DCF', 'Dir. Financière(DCF)'), ('DRH', 'Dir. RH(DRH)'), ('DEX', 'Dir. Exploitation(DEX)'), ('DET', 'Dir. Technique(DET)'), ('DCM', 'Dir. Commerciale(DCM)'), ('SMG', 'Moyens Generaux(SMG)'), ('FHY', 'fret Hydrocarbure(FHY)'), ('FSB', 'fret boisson(FSB)'), ('FHP', 'fret huile de palm(FHP)'), ('FTC', 'fret conteneurs(FTC)'), ('FCS', 'fret canne à sucre(FCS)'), ('FDI', 'fret divers(FDI)'), ('LEV', 'levage(LEV)'), ('LOC', 'location de surfaces(LOC)'), ('SDI', 'services divers(SDI)'), ('RAV', 'revenus à ventiler(RAV)'), ('PAF', 'Prestation Accessoir(PAF)'), ('COL', 'fret Colis lourds(COL)')], default='DGE', max_length=3, verbose_name='activité')),
                ('agency', models.CharField(blank=True, choices=[('0000', 'Siège'), ('0001', 'Abidjan (agence principale)'), ('0002', 'Bouaflé'), ('0003', 'San-Pedro'), ('0007', 'Bouaké'), ('0008', 'Yamoussoukro'), ('0009', 'Ferké'), ('0010', 'Minautores')], default='0001', max_length=4, verbose_name='agence')),
                ('date', models.DateTimeField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('a_rembourser', models.BooleanField(default=False, verbose_name='A rembourser')),
                ('axe_analyse', models.CharField(blank=True, choices=[('200', 'Batiment et charge locative'), ('210', 'Voyage & deplacement'), ('220', 'Fourniture & consommable de bureau'), ('230', 'Charge personnel'), ('240', 'Quote-part depreciation immo'), ('250', 'Personnel & services exterieur'), ('260', 'Relation exterieur'), ('270', 'Impôt & taxes'), ('280', 'Autres charges directions et service'), ('900', "Recette d'exploitation"), ('910', 'Frais/Opération (frais voyages)'), ('920', 'Papier administratif-CR'), ('930', "Main d'oevre dédiée"), ('940', 'Quote-part amortissement CR et autres'), ('950', 'Entretien & reparation CR'), ('960', 'Frais generaux')], max_length=255, verbose_name='Axe analyse')),
                ('validated', models.BooleanField(default=False, verbose_name='Validée')),
                ('refused', models.BooleanField(default=False, verbose_name='Refusée')),
                ('en_attente', models.BooleanField(default=True, verbose_name='En attente')),
                ('code_vehicule', models.CharField(blank=True, max_length=50, verbose_name='Code véhicule')),
                ('code_remorque', models.CharField(blank=True, max_length=50, verbose_name='Code remorque')),
                ('imat_vehicule', models.CharField(blank=True, max_length=50, verbose_name='Imat. véhicule')),
                ('imat_remorque', models.CharField(blank=True, max_length=50, verbose_name='Imat. Remorque')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chauffeur', verbose_name='Chauffeur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
            },
        ),
        migrations.CreateModel(
            name='FeeReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('PSE', 'PESAGE'), ('PGE', 'PEAGE'), ('SBK', 'SEJOUR BOUAKE'), ('TXI', 'TAXI')], max_length=3, verbose_name='Libelle')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('price', models.FloatField(default=0, verbose_name='Montant')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FeeRequest', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Motif',
                'verbose_name_plural': 'Motifs',
            },
        ),
    ]
