# Generated by Django 3.0 on 2021-04-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210428_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feerequest',
            old_name='description',
            new_name='commentaire',
        ),
    ]
