# Generated by Django 3.0 on 2021-04-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210428_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feerequest',
            old_name='motif_refus',
            new_name='observation_admin',
        ),
    ]
