# Generated by Django 3.0 on 2021-04-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210428_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerequest',
            name='level1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feerequest',
            name='level2',
            field=models.BooleanField(default=False),
        ),
    ]
